### PR TITLE
fix scary permissions

### PR DESCRIPTION
**Pull request by ubragg**
Due to
https://code.google.com/p/google-apps-script-issues/issues/detail?id=435
4, the word “enable” makes the Chrome Web Store think this permission
needs a super scary permission about app deployment.  Simply changing
this word in the comment fixes the issue.

### CODE REVIEW

**Review by derricks — APPROVED** [review]
Good to know about!

**Comment by derricks** [comment]
Odd that you should need to rebase; I've not touched this since your changes

**Comment by ubragg** [comment]
I didn't think I did rebase...

**Comment by ubragg** [comment]
Give me a sec and I'll work this out.

**Comment by ubragg** [comment]
OK, merge away.  I'm really not sure what happened there.

**Pull request merged**
